import type { Course } from "@/types/course";

/**
 * Creates a fully typed mock Course object with sensible defaults.
 */
export function createMockCourse(overrides: Partial<Course> = {}): Course {
  return {
    id: "course-mock-1",
    name: "Mock Dog Training Course",
    certifiedTrainer: false,
    certifierName: null,
    trainerExperienceDescription: null,
    veterinaryTraining: false,
    veterinaryTrainingCertifier: null,
    veterinaryTrainingDetails: null,
    dedicatedField: false,
    trainingFieldDescription: null,
    trainingFieldAddress: null,
    trainingFieldGoogleBusinessProfile: null,
    trainingFieldGoogleMapsLink: null,
    parking: false,
    parkingDescription: null,
    details: "Default course details description",
    termsOfParticipation: "Default terms of participation",
    price: "100",
    priceType: "course",
    medicationAdministration: false,
    medicationAdministrationDetails: null,
    surveillance247: false,
    surveillance247Details: null,
    webCam: false,
    webCamDetails: null,
    dailyWalks: 1,
    ownerCommunication: false,
    ownerCommunicationDetails: null,
    personalizedMealPlan: false,
    personalizedMealPlanDetails: null,
    emergencyVetTransport: false,
    emergencyVetTransportDetails: null,
    plantWatering: false,
    plantWateringDetails: null,
    nonSmoker: false,
    spokenLanguages: null,
    maxPetsPerVisit: 1,
    additionalPetPolicy: null,
    checkin: "08:00",
    checkout: "18:00",
    checkinWeekend: "09:00",
    checkoutWeekend: "16:00",
    schedule: null,
    ageLimitsEnabled: false,
    ageLimits: null,
    acceptedDogSizesEnabled: false,
    acceptedDogSizes: null,
    trainingFormat: "Group Class",
    maxDogsPerGroup: 6,
    indoorFacility: false,
    indoorFacilityDescription: null,
    playYard: false,
    playYardDetails: null,
    pool: false,
    poolDetails: null,
    socializationPolicy: null,
    coverageZones: null,
    faq: null,
    ...overrides,
  };
}
