/**
 * Map of Top 40 Romanian Cities + Bucharest and their respective cartiere (neighborhoods).
 * Used for neighborhood/zone coverage selection in Dog Walking services.
 */

export const ROMANIAN_CITY_CARTIERE: Record<string, string[]> = {
  București: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Aviatorilor",
    "Aviației",
    "Băneasa",
    "Berceni",
    "Bucureștii Noi",
    "Colentina",
    "Cotroceni",
    "Crângași",
    "Dristor",
    "Drumul Taberei",
    "Dămăroaia",
    "Floreasca",
    "Ghencea",
    "Giulești",
    "Iancului",
    "Lipscani (Centru)",
    "Militari",
    "Moșilor",
    "Obor",
    "Pantelimon",
    "Pipera",
    "Rahova",
    "Titan",
    "Vitan",
  ],
  "Cluj-Napoca": [
    "Centru",
    "Mănăștur",
    "Gheorgheni",
    "Mărăști",
    "Zorilor",
    "Grigorescu",
    "Bună Ziua",
    "Andrei Mureșanu",
    "Europa",
    "Iris",
    "Dâmbul Rotund",
    "Someșeni",
    "Borhanci",
    "Sopor",
    "Plopilor",
    "Gruia",
    "Între Lacuri",
    "Făget",
    "Bulgaria",
    "Becaș",
  ],
  Timișoara: [
    "Centru",
    "Iosefin",
    "Elisabetin",
    "Fabric",
    "Mehala",
    "Freidorf",
    "Fratelia",
    "Girocului",
    "Soarelui",
    "Complex Studențesc",
    "Dâmbovița",
    "Lipovei",
    "Aradului",
    "Torontalului",
    "Steaua",
    "Calea Șagului",
    "Plopi",
    "Kuncz",
  ],
  Iași: [
    "Centru",
    "Copou",
    "Tătărași",
    "Nicolina",
    "Alexandru cel Bun",
    "Păcurari",
    "Cantemir",
    "Galata",
    "Canta",
    "Dacia",
    "Tudor Vladimirescu",
    "Bucium",
    "Moara de Vânt",
    "Bularga",
    "Mircea cel Bătrân",
  ],
  Constanța: [
    "Centru",
    "Tomis I",
    "Tomis II",
    "Tomis III",
    "Tomis IV",
    "Tomis Nord",
    "Mamaia",
    "Faleză Nord",
    "Faleză Sud (Poarta 6)",
    "Coiciu",
    "Palas",
    "Km 4-5",
    "Km 5",
    "Inel I",
    "Inel II",
    "Abator",
    "Tăbăcărie",
    "Bora",
  ],
  Craiova: [
    "Centru",
    "Craiovița Nouă",
    "Brazda lui Novac",
    "Rovine",
    "Lăpuș",
    "1 Mai",
    "Vale Roșie",
    "Romanești",
    "Bariera Vâlcii",
    "Sărari",
    "Bordei",
    "Catargiu",
    "Podari",
  ],
  Brașov: [
    "Centru Vechi (Șchei)",
    "Civic Center",
    "Astra",
    "Tractorul",
    "Florilor",
    "Craiter",
    "Noua",
    "Darste",
    "Bartolomeu",
    "Stupini",
    "Valea Cetății (Răcădău)",
    "Triaj",
    "Blumăna",
  ],
  Galați: [
    "Centru",
    "Mazepa I",
    "Mazepa II",
    "Țiglina I",
    "Țiglina II",
    "Țiglina III",
    "Micro 16",
    "Micro 17",
    "Micro 18",
    "Micro 19",
    "Micro 20",
    "Micro 21",
    "Micro 39",
    "Siderurgiștilor Nord",
    "Port",
    "Filești",
  ],
  Ploiești: [
    "Centru",
    "Nord",
    "Sud",
    "Vest",
    "Mihai Bravu",
    "Republicei",
    "Bariera București",
    "Bereasca",
    "Democrației",
    "Bariera Rudului",
    "Bariera Unirii",
  ],
  Oradea: [
    "Centru",
    "Nufărul",
    "Rogerius",
    "Iosia",
    "Cantemir",
    "Velența",
    "Oncea",
    "Epitropiei",
    "Subcetate",
    "Vie",
  ],
  Brăila: [
    "Centru",
    "Hipodrom",
    "Vidin",
    "Progresul",
    "Călărași IV",
    "Obor",
    "Chercea",
    "Radu Negru",
    "Viziru",
    "Bariera Călărașilor",
  ],
  Arad: [
    "Centru",
    "Micălaca",
    "Alfa",
    "Vlaicu (Aurel Vlaicu)",
    "Pârneava",
    "Gradiste",
    "Aradul Nou",
    "Sânnicolau Mic",
    "Bujac",
    "Gai",
  ],
  Pitești: [
    "Centru",
    "Găvana",
    "Trivale",
    "Craiovei",
    "Prundu",
    "Popa Șapcă",
    "Războieni",
    "Exercițiu",
    "Ceair",
    "Nord",
  ],
  Sibiu: [
    "Centru Istoric",
    "Hipodrom I",
    "Hipodrom II",
    "Hipodrom III",
    "Vasile Aaron",
    "Terezian",
    "Țiglari",
    "Turnișor",
    "Valea Aurie",
    "Strand",
    "Lazaret",
    "Gușterița",
    "Treboniu Laurean",
  ],
  Bacău: [
    "Centru",
    "Nord",
    "Republicii",
    "Cornisa",
    "Izvoare",
    "Mioriței",
    "Șerbănești",
    "Letea",
    "Gherăiești",
    "Ura",
  ],
  "Târgu Mureș": [
    "Centru",
    "Tudor Vladimirescu",
    "Dâmbu Pietros",
    "7 Noiembrie",
    "Carpați",
    "Cornisa",
    "Unirii",
    "Rovinari",
    "Budiului",
  ],
  "Baia Mare": [
    "Centru Vechi",
    "Centru Nou",
    "Săsar",
    "Hatvan",
    "Progresului",
    "Vasile Alecsandri",
    "Griviței",
    "Ferneziu",
    "Firiza",
  ],
  Buzău: [
    "Centru",
    "Micro 3",
    "Micro 5",
    "Micro 14",
    "Dorobanți",
    "Broșteni",
    "Simileasca",
    "Unirii",
    "Poșta",
  ],
  Botoșani: [
    "Centru",
    "Bucovina",
    "Grivița",
    "Primăverii",
    "Ștefan cel Mare",
    "Marchian",
    "Tulbureni",
    "Capătul lui 1",
  ],
  "Satu Mare": [
    "Centru",
    "Micro 14",
    "Micro 15",
    "Micro 16",
    "Micro 17",
    "Solidarității",
    "Carpati I",
    "Carpati II",
    "16 Mai",
  ],
  "Râmnicu Vâlcea": [
    "Centru",
    "Ostroveni",
    "Traian",
    "Nord",
    "1 Mai",
    "Goranu",
    "Călina",
    "Petrișor",
  ],
  Suceava: [
    "Centru",
    "Burdujeni",
    "Itcani",
    "George Enescu",
    "Obcini",
    "Zamca",
    "Mărășești",
    "Areni",
  ],
  Focșani: [
    "Centru",
    "Sud",
    "Nord",
    "Gării",
    "Bahne",
    "Mândrești",
    "Obor",
  ],
  "Piatra Neamț": [
    "Centru",
    "Dărmănești",
    "Precista",
    "Mărăței",
    "1 Mai",
    "Sărata",
    "Văleni",
  ],
  "Drobeta-Turnu Severin": [
    "Centru",
    "Kiseleff",
    "Crișan",
    "Schela Cladovei",
    "Aluniș",
    "Calea Timișoarei",
  ],
  "Târgu Jiu": [
    "Centru",
    "Debarcader",
    "Abator",
    "9 Mai",
    "CAM",
    "Lido",
    "Vădeni",
  ],
  Tulcea: [
    "Centru",
    "E3",
    "West City",
    "Babadag",
    "Port",
    "Neptun",
  ],
  Târgoviște: [
    "Centru",
    "Micro 6",
    "Micro 11",
    "Micro 12",
    "Sârbi",
    "Matei Basarab",
  ],
  Bistrița: [
    "Centru",
    "Ștefan cel Mare",
    "Progresului",
    "Subcetate",
    "Decebal",
    "Viișoara",
    "Unirea",
  ],
  Reșița: [
    "Centru",
    "Lunca Bârzavei (Govândari)",
    "Muncitoresc",
    "Stavila",
    "Secu",
    "Cuptoare",
  ],
  Slatina: [
    "Centru",
    "Steaua",
    "Progresul",
    "Crișan",
    "Clocociov",
  ],
  Hunedoara: [
    "Centru",
    "Micro 5",
    "OMV",
    "Zăvoi",
    "Chizid",
    "Peștișu Mare",
  ],
  Vaslui: [
    "Centru",
    "13 Decembrie",
    "Gura Bustei",
    "Gării",
    "Brodoc",
  ],
  Călărași: [
    "Centru",
    "Orizont",
    "2 din 4",
    "Măgureni",
    "Mircea Vodă",
  ],
  Giurgiu: [
    "Centru",
    "Tineretului",
    "1 Mai",
    "Smârda",
    "Ramadan",
  ],
  Roman: [
    "Centru",
    "Favorit",
    "Smirodava",
    "Miron Costin",
    "Dărmănești",
  ],
  Deva: [
    "Centru",
    "Gojdu",
    "Micro 15",
    "Dacia",
    "Zăvoi",
    "Progresul",
  ],
  Bârlad: [
    "Centru",
    "Munteni",
    "Podeni",
    "Gării",
    "Deal",
  ],
  "Alba Iulia": [
    "Centru",
    "Cetate",
    "Ampoi I",
    "Ampoi II",
    "Ampoi III",
    "Micești",
    "Barabanț",
    "Oarda",
  ],
  Voluntari: [
    "Centru",
    "Pipera",
    "Matei Millo",
    "Cazangiilor",
    "Băneasa Nord",
  ],
  "Sfântu Gheorghe": [
    "Centru",
    "Simeria",
    "Gării",
    "Ciucului",
    "Lunca Oltului",
  ],
  Turda: [
    "Centru",
    "Oprișani",
    "Micro 1",
    "Micro 2",
    "Micro 3",
    "Poiana",
    "Turda Nouă",
  ],
  Mediaș: [
    "Centru",
    "Vitrometan",
    "Gura Câmpului",
    "După Zid",
    "Wewer",
    "Moșna",
    "Automecanica",
  ],
  Sighișoara: [
    "Cetate",
    "Centru Istoric",
    "Târnava",
    "Cornești",
    "Viilor",
    "Barați",
  ],
  Petroșani: [
    "Centru",
    "Livezeni",
    "Aeroport",
    "Dacia",
    "Dimitrov",
    "Colonie",
  ],
  Lugoj: [
    "Centru",
    "Cotu Mic",
    "Stadion",
    "Mondial",
    "Micro 1",
    "Micro 2",
    "Ștreang",
  ],
  Mioveni: [
    "Centru",
    "Clucereasa",
    "Racovița",
    "Făget",
    "Colibași",
  ],
  Câmpina: [
    "Centru",
    "Turnătorie",
    "Slobozia",
    "Voila",
    "Muscel",
    "Fibra",
  ],
  Caracal: [
    "Centru",
    "HCC",
    "Protopopiat",
    "Libertății",
    "Gară",
    "Bold",
  ],
  Câmpulung: [
    "Centru",
    "Vișoi",
    "Schei",
    "Grui",
    "Mărcuș",
  ],
  Mangalia: [
    "Centru",
    "Saturn",
    "Venus",
    "Cap Aurora",
    "Neptun",
    "Olimp",
    "Nord",
    "Coloniști",
  ],
  Făgăraș: [
    "Centru",
    "13 Decembrie",
    "Combinat",
    "Galați",
    "Negoiu",
    "Tudor Vladimirescu",
  ],
  Dej: [
    "Centru",
    "Mulatău",
    "Triaj",
    "Viile Dejului",
    "Zăvoi",
  ],
  Săcele: [
    "Centru",
    "Electroprecizia",
    "Movilei",
    "Baciu",
    "Turcheș",
    "Cernatu",
  ],
  Năvodari: [
    "Centru",
    "Mamaia Nord",
    "Peninsula",
    "Usas",
    "Est",
  ],
  Pașcani: [
    "Centru",
    "Gării",
    "Vatra",
    "Blăgești",
    "Lunca",
    "Boșteni",
  ],
  Reghin: [
    "Centru",
    "Iernuțeni",
    "Apalina",
    "Rodnei",
    "Unirii",
  ],
  "Câmpia Turzii": [
    "Centru",
    "Insula",
    "Lut",
    "Șarcău",
    "Șesani",
  ],
  Sebeș: [
    "Centru",
    "Lucian Blaga",
    "Mihail Kogălniceanu",
    "Petrești",
    "Lancrăm",
  ],
  "Curtea de Argeș": [
    "Centru",
    "Ivancea",
    "Marina",
    "Zăvoi",
    "Posada",
  ],
  "Târgu Neamț": [
    "Centru",
    "Condreni",
    "Humulești",
    "Blebea",
    "Țuțuieni",
  ],
  Huși: [
    "Centru",
    "Dric",
    "Corni",
    "Plopilor",
    "Gară",
  ],
  Vulcan: [
    "Centru",
    "Micro 1",
    "Micro 2",
    "Crividia",
    "Dallas",
    "Paroșeni",
  ],
  Lupeni: [
    "Centru",
    "Straja",
    "Braia",
    "Bărbeni",
    "Viitorului",
  ],
  Cugir: [
    "Centru",
    "Râul Mare",
    "Vinerea",
    "Micro",
    "Călușeri",
  ],
  Rădăuți: [
    "Centru",
    "Obor",
    "Hipodrom",
    "Volovăț",
    "Calea Cernăuți",
  ],
  "Miercurea Ciuc": [
    "Centru",
    "Spitalului",
    "Băile Miercurea",
    "Jigodin",
    "Șumuleu",
    "Cioboteni",
  ],
  "Sighetu Marmației": [
    "Centru",
    "Câmpu Neagului",
    "Iezer",
    "Solovan",
    "Valea Cufundoasă",
  ],
  Dorohoi: [
    "Centru",
    "Plevna",
    "Trestiana",
    "Progresul",
    "Decebal",
  ],
  Fălticeni: [
    "Centru",
    "Țarna Mare",
    "Maior Ioan",
    "Soldat Dumitru",
    "Șoldănești",
  ],
  Târnăveni: [
    "Centru",
    "Cuza Vodă",
    "Bozieș",
    "Armata",
    "Bărăbanț",
  ],
  Gherla: [
    "Centru",
    "Băi",
    "Hașdate",
    "Silivaș",
    "Candia",
  ],
  Codlea: [
    "Centru",
    "Colorom",
    "Măgura",
    "Gară",
    "Oituz",
  ],
  Zărnești: [
    "Centru",
    "Tohanu Nou",
    "Tohanu Vechi",
    "6 Martie",
    "Celulozei",
  ],
  Moreni: [
    "Centru",
    "Schela",
    "Tisa",
    "Stavropoleos",
    "Țuicani",
  ],
  Marghita: [
    "Centru",
    "Cheșereu",
    "Ghenetea",
    "Viilor",
    "Barcăului",
  ],
  Carei: [
    "Centru",
    "Iancu Jianu",
    "1 Mai",
    "Mihai Viteazul",
    "Eliberării",
  ],
  Cernavodă: [
    "Centru",
    "Trust",
    "Columbia",
    "Ideal",
    "Gară",
  ],
  Băicoi: [
    "Centru",
    "Schela",
    "Liliești",
    "Țintea",
    "Dâmbu",
  ],
  Băilești: [
    "Centru",
    "Gară",
    "Boureni",
    "Independenței",
    "Victoriei",
  ],
  Buftea: [
    "Centru",
    "Flămânzeni",
    "Buciumeni",
    "Studioului",
    "Crețulești",
  ],
  Măgurele: [
    "Centru",
    "Atomiștilor",
    "Pruni",
    "Vârteju",
    "Dumitrana",
  ],
  Otopeni: [
    "Centru",
    "Odăi",
    "Ferme",
    "Aeroport",
    "23 August",
  ],
  "Pantelimon (Oraș)": [
    "Centru",
    "Sfântul Pantelimon",
    "Viilor",
    "Cernica",
    "Lebăda",
  ],
  "Popești-Leordeni": [
    "Centru",
    "Danubiu",
    "Leordeni",
    "Drumul Fermei",
    "Sfânta Agnes",
  ],
  Bragadiru: [
    "Centru",
    "Cristalului",
    "Independenței",
    "Alexandriei",
    "Smârdan",
  ],
  Chitila: [
    "Centru",
    "Rudeni",
    "Traian",
    "Tineretului",
    "Gării",
  ],
  Luduș: [
    "Centru",
    "Gheorghe Doja",
    "1 Decembrie",
    "Roșiori",
    "Avram Iancu",
  ],
  Salonta: [
    "Centru",
    "Aradului",
    "Oradiei",
    "Gării",
    "Tinereții",
  ],
  "Câmpulung Moldovenesc": [
    "Centru",
    "Capu Satului",
    "Izvorul Alb",
    "Bodea",
    "Hurghiș",
  ],
  "Vatra Dornei": [
    "Centru",
    "Roșu",
    "Argestru",
    "Chilia",
    "Unirii",
  ],
  "Gura Humorului": [
    "Centru",
    "Voroneț",
    "Boureni",
    "Pyramida",
    "Mănăstirea",
  ],
  Blaj: [
    "Centru",
    "Veza",
    "Tiur",
    "Izvoarele",
    "Mănăstire",
  ],
  Aiud: [
    "Centru",
    "Ciumbrud",
    "Aiudul de Sus",
    "Măgina",
    "Gâmbaș",
  ],
  "Băile Herculane": [
    "Centru Istoric",
    "Centru Nou",
    "Pecinișca",
    "Saivan",
    "UGSR",
  ],
  Orșova: [
    "Centru",
    "Sud",
    "Nord",
    "Jupalnic",
    "Poșta",
  ],
  "Târgu Secuiesc": [
    "Centru",
    "Lunga",
    "Kanta",
    "Russell",
    "Gării",
  ],
  Gheorgheni: [
    "Centru",
    "Bucin",
    "Lăzarea",
    "Spitalului",
    "Florilor",
  ],
  "Odorheiu Secuiesc": [
    "Centru",
    "Budvar",
    "Bethlen",
    "Subcetate",
    "Cuza Vodă",
  ],
  Calafat: [
    "Centru",
    "Ciupercenii Vechi",
    "Basarabi",
    "Golenti",
    "Gară",
  ],
  "Turnu Măgurele": [
    "Centru",
    "Odaia",
    "Tabăra",
    "Catanga",
    "Gară",
  ],
};

/**
 * Normalizes a city name for diacritic-insensitive and case-insensitive comparison.
 */
export function normalizeCityName(cityName: string): string {
  if (!cityName) return "";
  return cityName
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "");
}

/**
 * Retrieves the cartiere array for a given city name if present in the dataset.
 */
export function getCartiereForCity(cityName: string): string[] | null {
  if (!cityName) return null;
  const targetKey = normalizeCityName(cityName);
  for (const key of Object.keys(ROMANIAN_CITY_CARTIERE)) {
    if (normalizeCityName(key) === targetKey) {
      return ROMANIAN_CITY_CARTIERE[key];
    }
  }
  return null;
}

/**
 * Returns whether a given city name is present in the top 41 cities dataset.
 */
export function isCitySupported(cityName: string): boolean {
  return getCartiereForCity(cityName) !== null;
}
